# Generated by Django 5.1.1 on 2024-11-19 05:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('DOB', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('start_year_of_practice', models.IntegerField()),
                ('availability_hours', models.JSONField(blank=True, default=list)),
                ('specialization', models.CharField(max_length=255)),
                ('study_history', models.JSONField(blank=True, default=list)),
                ('password', models.CharField(max_length=255)),
                ('hospital', models.CharField(max_length=255)),
                ('patients', models.ManyToManyField(related_name='doctors', to='patients.patient')),
            ],
        ),
    ]
