# Generated by Django 5.1.1 on 2024-11-19 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='study_history',
        ),
    ]
