# Generated by Django 5.1.1 on 2024-10-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_dob_alter_patient_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=100, unique=True)),
                ('patient_username', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('heart_rate', models.IntegerField()),
                ('o2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
