# Generated by Django 5.1.1 on 2024-11-18 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_recordeddata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctors',
        ),
    ]
