# Generated by Django 5.1.1 on 2024-10-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('start_year_of_practice', models.IntegerField()),
                ('availability_hours', models.JSONField(blank=True, default=list)),
                ('specialization', models.CharField(max_length=255)),
                ('study_history', models.JSONField(blank=True, default=list)),
                ('patients', models.JSONField(blank=True, default=list)),
                ('password', models.CharField(max_length=255)),
                ('hospital', models.CharField(max_length=255)),
            ],
        ),
    ]
