# Generated by Django 5.1.1 on 2024-10-31 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='DOB',
            field=models.CharField(max_length=50),
        ),
    ]
