# Generated by Django 5.1.1 on 2024-11-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_dob'),
        ('patients', '0004_remove_patient_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='patients',
        ),
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(related_name='doctors', to='patients.patient'),
        ),
    ]
