# Generated by Django 5.1.1 on 2024-11-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_remove_doctor_patients_doctor_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
